safe:        false
port: 4000
baseurl:     /laravelLearningBlog
url:         http://fanshine.github.io/laravelLearningBlog/


github: [Repository metadata]

author:
  name:      fanshine
  blog:      Laravel 知识整理
  email1:    fanshine124@gmail.com
  email2:    fanshine124[at]gmail.com

feed:        /atom.xml

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    rdiscount
permalink:   /:year-:month-:day/:title.html

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    laravelLearningBlog/images/latex
  png_url:    /laravelLearningBlog/images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  use_coderay:   false

coderay:
    coderay_wrap:               div
    coderay_line_numbers:       inline
    coderay_line_numbers_start: 1
    coderay_tab_width:          4
    coderay_bold_every:         10
    coderay_css:                style
